#!/usr/bin/perl -w
# Copyright 2009 Kevin Spencer <kevin@kevinspencer.org>
#
# Permission to use, copy, modify, distribute, and sell this software and its
# documentation for any purpose is hereby granted without fee, provided that
# the above copyright notice appear in all copies and that both that
# copyright notice and this permission notice appear in supporting
# documentation.  No representations are made about the suitability of this
# software for any purpose.  It is provided "as is" without express or 
# implied warranty.
#
################################################################################

use DBI;
use strict;

our $VERSION = '0.01';

# edit accordingly...
my $dsn  = '';
my $user = '';
my $pass = '';

my $dbh = DBI->connect($dsn, $user, $pass) ||
    die "Could not connect to $dsn - $DBI::errstr\n";

my $SQL = <<EOSQL;
update mt_entry
set entry_allow_comments = 0
where entry_created_on <= date_sub(CURDATE(), interval 20 day)
and entry_allow_comments <> 0
EOSQL

my $sth = $dbh->prepare($SQL) || die "$DBI::errstr\n";
$sth->execute() || die $sth->errstr(), "\n";
